# Generated by Django 3.1.12 on 2025-09-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_missing_fields'),
    ]

    operations = [
    ]
