# Generated by Django 3.1.12 on 2025-09-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250924_0609'),
        ('core', '0003_hospital_latitude_hospital_longitude_and_more'),
    ]

    operations = [
    ]
