# Generated by Django 3.1.12 on 2025-09-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20250925_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_card_image',
        ),
    ]
